INSERT INTO TB_VEICULO (marca, modelo, ano) VALUES ('Toyota', 'Corolla', 2020);
INSERT INTO TB_VEICULO (marca, modelo, ano) VALUES ('Honda', 'Civic', 2019);
INSERT INTO TB_VEICULO (marca, modelo, ano) VALUES ('Ford', 'Focus', 2018);
INSERT INTO TB_VEICULO (marca, modelo, ano) VALUES ('Chevrolet', 'Malibu', 2021);
INSERT INTO TB_VEICULO (marca, modelo, ano) VALUES ('Nissan', 'Altima', 2020);
INSERT INTO TB_VEICULO (marca, modelo, ano) VALUES ('Hyundai', 'Elantra', 2019);
INSERT INTO TB_VEICULO (marca, modelo, ano) VALUES ('Kia', 'Optima', 2018);
INSERT INTO TB_VEICULO (marca, modelo, ano) VALUES ('Volkswagen', 'Jetta', 2021);
INSERT INTO TB_VEICULO (marca, modelo, ano) VALUES ('Subaru', 'Impreza', 2020);
INSERT INTO TB_VEICULO (marca, modelo, ano) VALUES ('Mazda', 'Mazda3', 2019);
INSERT INTO TB_VEICULO (marca, modelo, ano) VALUES ('BMW', '3 Series', 2021);
INSERT INTO TB_VEICULO (marca, modelo, ano) VALUES ('Mercedes-Benz', 'C-Class', 2020);
INSERT INTO TB_VEICULO (marca, modelo, ano) VALUES ('Audi', 'A4', 2019);
INSERT INTO TB_VEICULO (marca, modelo, ano) VALUES ('Lexus', 'IS', 2018);
INSERT INTO TB_VEICULO (marca, modelo, ano) VALUES ('Acura', 'TLX', 2021);
INSERT INTO TB_VEICULO (marca, modelo, ano) VALUES ('Infiniti', 'Q50', 2020);
INSERT INTO TB_VEICULO (marca, modelo, ano) VALUES ('Cadillac', 'ATS', 2019);
INSERT INTO TB_VEICULO (marca, modelo, ano) VALUES ('Volvo', 'S60', 2018);
INSERT INTO TB_VEICULO (marca, modelo, ano) VALUES ('Jaguar', 'XE', 2021);
INSERT INTO TB_VEICULO (marca, modelo, ano) VALUES ('Alfa Romeo', 'Giulia', 2020);
INSERT INTO TB_VEICULO (marca, modelo, ano) VALUES ('Tesla', 'Model 3', 2021);
INSERT INTO TB_VEICULO (marca, modelo, ano) VALUES ('Chevrolet', 'Bolt', 2020);
